server:
  port: 7081
spring:
  profiles:
    active: dev
eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address} # 这里不能写成ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false # 是否将自己注册到eureka中
    fetch-registry: false # 是否从eureka中获取信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://127.0.0.1:${server.port}/eureka/