server:
  port: 8888

spring:
  application:
    name: config
  profiles:
    active: dev
  config:
    server:
      git: https://github.com/LantzShaw/
    label: master


eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka
